# Generated by Django 4.1.5 on 2023-01-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
